### ISSUE TITLE
申请添加下列已做好的物品标签

### ISSUE THREAD

**Issue by CR-019** [ououn/UIN#5]
检索了一遍物品表，制作了以下物品标签，请求最好全数添加进uin内，因为我即将发布的数据包需要用到这些标签.感激不尽。

建议添加：uin:general  ：
banners 旗帜
beds 床
boats 船
fishing_rods 钓鱼竿（包括钓竿、胡萝卜钓竿和诡异菌钓竿）
music_discs 音乐唱片
potions 药水（包括普通药水、喷溅型、滞留型）
signs 告示牌
建议添加：uin:tech  ：
1x 不可堆叠
16x 以16个为一组堆叠

在某些标签下，空开一行，表示空行下面是1.16新增的物品，去除之即为适用于1.15及以下版本的标签。

时间匆忙，可能有遗漏，请核查。
在1x标签里引用了uin的桶标签，但其中桶是以16个为一组堆叠的，我现在无暇修改，建议修改。

[items.zip](https://github.com/ououn/UIN/files/5971851/items.zip)

**Comment by ououn** [comment]
感谢，堆叠检查完了，已补上缺失部分并添加到全家桶

部分原版已有

当前main已添加
uin:general/potions
uin:general/fishing_rods
uin:tech/x_1
uin:tech/x_16
uin:tech/x_64

*当前main中属于1.17的新id仍在归类中，暂未发布，可考虑自行下载当前main，见谅
